# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    admin.ctlsexo:
        class: App\Admin\CtlSexoAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\CtlSexo, manager_type: orm, group: 'Catálogos', label: Sexo }
            
    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~, '@service_container']
        calls:
            #- [setTemplate, ['edit', 'User/edit.html.twig']]
        tags:
        - { name: sonata.admin, manager_type: orm, group: admin, label: users }

    admin.role:
        class: App\Admin\RoleAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Role, controller: ~, manager_type: orm, group: admin, label: Role }
